### ISSUE TITLE
Question: Auction API Integration?

### ISSUE THREAD

**Issue by HuntBurdick** [elightup/auto-listings#5]
Hello all, thanks for your hard work. I've used the plugin in the past. Currently I'm working on a wholesale automotive auction marketplace and we have an API to publish and manage vehicles on our platform. If I wanted to create an integration with auto-listings to provide that functionality to your users, what would be the best approach? Is it possible? Do I have permission?

The added functionality would allow auto-listings users to push old age inventory to our auction marketplace for wholesale sale.

**Comment by rilwis** [comment]
Hi @HuntBurdick ,

> If I wanted to create an integration with auto-listings to provide that functionality to your users, what would be the best approach? Is it possible? Do I have permission?

We welcome all the integration with our plugin.

Personally, I think it depends on what you're trying to do with the integration (in details). I guess REST API is the best way to handle that. You might want to contribute to the plugin to add the endpoints/APIs you want (and we always welcome that).
